---
title: "Compute IR Populations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

# Load relevant functions
source("../src/R/compute_ir_populations_fns.R")

# Set data directory path
datadir <- "/project/cil/gcp/population/"

# Select data products and years
products <- c("landscan")
years <- c(2015, 2020, 2022)
```

```{r hist-ir-level processing, eval = T}
# Create full set of products and years
specs <- expand_grid(
  datadir = datadir,
  product = products, 
  year = years)

# Compute IR-level populations
pops <- specs %>% 
  mutate(
    # Sum population within each IR
    unscaled_pop_df = pmap(., aggregate_pop_to_ir),
    
    # Scale IR populations to correspond with UN country population totals
    scaled_pop_df = map2(datadir, unscaled_pop_df, ~scale_ir_pop(.x, .y))
  ) %>% 
  # Extract IR-level population datasets
  pivot_longer(
    matches(".*pop_df$"), 
    values_to = "dfs") %>% 
  mutate(export_path = 
           str_c(datadir, file.path("processed", product, year, str_extract(name, "[a-z]+"))),
         .keep = "unused")

# Make export directories
if (!all(sapply(pops$export_path, dir.exists))) {
  pops %>% 
    filter(!dir.exists(export_path)) %>% 
    pull(export_path) %>% 
    map(~dir.create(.x, recursive = T))
}

# Export IR-level population data 
pops %>% 
  mutate(export_path = file.path(export_path, "ir_pop.csv")) %>% 
  mutate(return = map2(dfs, export_path, ~write_csv(.x, .y)))
 
```
