---
title: "Validate IR Populations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
source("../src/validate_ir_populations_fns.R")
source("../src/compute_ir_populations_fns.R")
datadir <- "/project/cil/gcp/population/"

```

# Product year selection 
```{r product-year selection}
ir_pop <- read_csv(str_c(datadir, "processed/ir_population_data.csv"), show_col_types = F) 

selected_products <- NULL
selected_years <- NULL

# Get product year combinations
plot_specs <- 
  ir_pop %>% 
  select(product, year) %>% 
  unique() %>% 
  mutate(ir_pop = list(ir_pop), .before = everything()) %>% 
  {if (!is.null(selected_products)) filter(., source %in% selected_products) else .} %>% 
  {if (!is.null(selected_years)) filter(., year %in% selected_years) else .}

```


# Density plots
## Difference of UN Country Population and Product Country Population
```{r validation-density plots diff, echo = F, warning = F, message = F}
pmap(plot_specs, make_pop_diff_density_plot)
```

## Ratio of UN Country Population and Product Country Population
```{r validation-density plots ratio, echo = F, warning = F, message = F}
pmap(plot_specs, make_pop_ratio_density_plot)
```


# Maps
```{r create simplified shp, echo = F}
simplified_shp <- load_simplified_shapefile(datadir)
```

## IR populations
```{r validation-pop maps raw, echo = F, warning = F, message = F, eval = T}
plot_specs %>% 
  mutate(simplified_shp = list(simplified_shp)) %>% 
  expand(rescaled = c(T,F), nesting(ir_pop, product, year, simplified_shp)) %>% 
  pmap(make_pop_plot) %>% 
  map(print)
```

## Difference between scaled and unscaled IR populations
```{r validation-pop maps diff, echo = F, warning = F, message = F, eval = T}
plot_specs %>% 
  mutate(simplified_shp = list(simplified_shp)) %>% 
  pmap(make_pop_diff_plot) %>% 
  map(print)
```

## % Difference of scaled and unscaled IR populations
```{r validation-pop maps ratio, echo = F, warning = F, message = F, eval = T}
plot_specs %>% 
  mutate(simplified_shp = list(simplified_shp)) %>% 
  pmap(make_pop_ratio_plot) %>% 
  map(print)
```


