---
title: "Compute IR Populations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(furrr)
source("compute_ir_populations_fns.R")
```

# Processing 
```{r processing}
# Get full set of products and years
products <- c("landscan")
years <- c(2015, 2020, 2022)
specs <- expand_grid(
  datadir = "/project/cil/gcp/population/",
  product = products, 
  year = years)

# Compute IR-level populations
par_workers <- min(nrow(specs), parallelly::availableCores() - 1)
plan(multisession, workers = par_workers)

pops <- specs %>% 
  mutate(
    unscaled_pop_df = furrr::future_pmap(., aggregate_pop_to_ir),
    scaled_pop_df = furrr::future_map2(datadir, unscaled_pop_df, ~scale_ir_pop(.x, .y))
  ) %>% 
  pivot_longer(
    matches("pop_df"), 
    values_to = "dfs") %>% 
  pull(dfs) %>% 
  bind_rows() %>% 
  rename(rescaled_to_sum_to_un_pop = rescaled)

# Export IR-level population data 
out_path <- "/project/cil/gcp/population/processed/ir_population_data.csv"
write_csv(pops, out_path)

```

# Validation
```{r validation}
# Get full set of products and years
products <- c("landscan")
years <- c(2015, 2020, 2022)
specs <- expand_grid(
  datadir = "/project/cil/gcp/population/",
  product = products, 
  year = years)

# Compute IR-level populations
par_workers <- min(nrow(specs), parallelly::availableCores() - 1)
plan(multisession, workers = par_workers)

pops <- specs %>% 
  mutate(
    unscaled_pop_df = furrr::future_pmap(., aggregate_pop_to_ir),
    scaled_pop_df = furrr::future_map2(datadir, unscaled_pop_df, ~scale_ir_pop(.x, .y))
  ) %>% 
  pivot_longer(
    matches("pop_df"), 
    values_to = "dfs") %>% 
  pull(dfs) %>% 
  bind_rows() %>% 
  rename(rescaled_to_sum_to_un_pop = rescaled)

# Export IR-level population data 
out_path <- "/project/cil/gcp/population/processed/ir_population_data.csv"
write_csv(pops, out_path)

```
